version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=api.absendulu.site
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=api.absendulu.site
      - LETSENCRYPT_EMAIL=system@absendulu.site

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-dhparam:/etc/nginx/dhparam
    networks:
      - nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt-companion
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - letsencrypt-acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=system@absendulu.site
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - nginx-proxy
    depends_on:
      - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-dhparam:
  letsencrypt-acme: