version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: unless-stopped
    expose:
      - "8083"
    networks:
      - proxy-tier
    environment:
      - VIRTUAL_HOST=api.absendulu.site
      - VIRTUAL_PORT=8083
      - LETSENCRYPT_HOST=api.absendulu.site
      - LETSENCRYPT_EMAIL=system@absendulu.site

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:

networks:
  proxy-tier:
    external: true