version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-absendulu-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
      - go-mod-cache:/go/pkg/mod
    env_file:
      - .env
    working_dir: /app
    networks:
      - app-network
    restart: unless-stopped
    tty: true
    stdin_open: true

networks:
  app-network:
    driver: bridge

volumes:
  go-mod-cache: